[project]
name = "avmpi_scripts"
version = "0.1.0"
description = "the home of the Smithsonian Library and Archives Audiovisual Media Preservation Initiative's software automations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annotated-types==0.7.0",
    "cachetools==5.3.3",
    "certifi==2024.2.2",
    "chardet==5.2.0",
    "charset-normalizer==3.3.2",
    "colorama==0.4.6",
    "coverage==7.5.1",
    "distlib==0.3.8",
    "et-xmlfile==1.1.0",
    "filelock==3.14.0",
    "idna==3.7",
    "inflection==0.5.1",
    "iniconfig==2.0.0",
    "openpyxl==3.1.2",
    "packaging==24.0",
    "platformdirs==4.2.2",
    "pluggy==1.5.0",
    "pyairtable==2.3.3",
    "pydantic-core>=2.35.2",
    "pyproject-api==1.6.1",
    "pytest==8.2.1",
    "pytest-cov==5.0.0",
    "requests==2.32.2",
    "tox==4.15.0",
    "urllib3==2.2.1",
    "virtualenv==20.26.2",
]
